Ofcourse/Ofcourse/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('courses/', include('courses.urls', namespace='courses')),
    path('', views.homepage, name='homepage'),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

Ofcourse/courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'
urlpatterns = [
    path("", views.course_list, name='list'),
    path("<int:course_pk>/<int:step_pk>/", views.step_detail, name='step_detail'),
    path("<int:pk>/", views.course_detail, name='course_detail'),
]

Ofcourse/courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

class Step(models.Model):
    title = models.CharField(max_length=255)
    descrition = models.TextField()
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.title

Ofcourse/Ofcourse/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

Ofcourse/courses/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Course, Step
# Create your views here.
def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})

def course_detail(request,pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

Ofcourse/courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %} {{ course.title }} {%endblock title %}

{% block content %}
<article>
  <h2>{{ course.title }}</h2>
  {{ course.description }}
  <section>
    {% for step in course.step_set.all %}
      <h3>
        <a href="{% url 'courses:step_detail' course_pk=step.course.pk step_pk=step.pk %}">
          {{ step.title }}
        </a>
      </h3>
      {{ step.descrition }}
    {% endfor %}
  </section>

</article>

{% endblock content %}

Ofcourse/courses/templates/courses/course_list.html
{% extends "layout.html" %}

{% block title %} Available courses {% endblock title %}

{% block content %}
<h1>Course catalog</h1>
<div class="cards">
  {% for course in courses %}
    <div class="card">
      <header>
        <a href="{% url 'courses:course_detail' pk=course.pk %}">{{ course.title }} </a>
      </header>
        <div class="card-copy">
          {{ course.description}}
        </div>


    </div>
  {% endfor %}
</div>
{% endblock content %}

Ofcourse/courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %} {{ step.title }} | {{ step.course.title }} {% endblock %}

{% block content %}
<article>
  <h2>
    <a href="{% url 'courses:course_detail' pk=step.course.pk %}">
      {{ step.course.title }}
    </a>
  </h2>
  <h3> {{ step.title }} </h3>
  <p> {{ step.descrition }}</p>
  {{ step.content|linebreaks }}
</article>
{% endblock %}

Ofcourse/templates/home.html
{% extends "layout.html" %}

{% block title %} Homepage {% endblock title %}

{% block content %}
<h1> Welcome home! </h1>
{% endblock content %}

Ofcourse/templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
  </head>
  <body>
    <nav>
      <a href="{% url 'homepage' %}">Home</a>
      <a href="{% url 'courses:list' %}">Courses</a>
    </nav>
    <div class="site-container">
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>